### ISSUE TITLE
Getting error while running the code as directed using tensorflow r 0.12.1

### ISSUE THREAD

**Issue by anshitm** [bamos/dcgan-completion.tensorflow#23] opened 2017-03-15 15:51 UTC
Traceback (most recent call last):

  File "./complete.py", line 33, in <module>
    dcgan = DCGAN(sess, image_size=args.imgSize,checkpoint_dir=args.checkpointDir, lam=args.lam)
  File "/home/anshit/Downloads/dcgan-completion.tensorflow-master/dcgan-completion.tensorflow-master/model.py", line 65, in __init__
    self.build_model()
  File "/home/anshit/Downloads/dcgan-completion.tensorflow-master/dcgan-completion.tensorflow-master/model.py", line 81, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=True)
  File "/home/anshit/Downloads/dcgan-completion.tensorflow-master/dcgan-completion.tensorflow-master/model.py", line 312, in discriminator
    h1 = lrelu(self.d_bn1(conv2d(h0, self.df_dim*2, name='d_h1_conv')))
  File "/home/anshit/Downloads/dcgan-completion.tensorflow-master/dcgan-completion.tensorflow-master/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)

ValueError: Variable d_bn1/d_bn1_2/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). 
Did you mean to set reuse=None in VarScope?

**Comment by bamos** [comment] 2017-03-15 15:52
This is a duplicate of #14

**Closed as completed by bamos** 2017-03-15 15:52 UTC

**Comment by anshitm** [comment] 2017-03-15 17:13
Yeah thanks it worked but now the trained models in checkpoint directory won't work. I am having an amd gpu so it would take very long time to re train on cpu........ any suggestions??
